include:
  - board: nice_nano@2.0.0
    shield: mdbt50q_dongle
    snippet: studio-rpc-usb-uart

  - board: nice_nano@2.0.0
    shield: sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano@2.0.0
    shield: sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
